/*
 * build.mjs
 * Walks the app, hashes it, and writes a service worker whose precache list is
 * always exactly what is on disk. Run this after touching any asset.
 *
 *   node build.mjs
 */

import { readdirSync, statSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, relative, sep } from 'node:path';

const ROOT = new URL('.', import.meta.url).pathname;

const SKIP_DIRS = new Set(['art', 'node_modules', '.git', '.github']);
const SKIP_FILES = new Set(['build.mjs', 'sw.js', '.DS_Store', 'README.md']);

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const rel = relative(ROOT, full).split(sep).join('/');
    if (statSync(full).isDirectory()) {
      if (!SKIP_DIRS.has(name) && !name.startsWith('.')) walk(full, out);
    } else if (!SKIP_FILES.has(name) && !name.startsWith('.')) {
      out.push(rel);
    }
  }
  return out;
}

const files = walk(ROOT).sort();

// Keep the install payload lean. The 1024 icon is only ever read by the
// manifest, and the seed books are fetched once on first run and then live in
// IndexedDB, so caching them too would store every one of them twice.
const DEAD = ['assets/beasts/'];   // kept on disk for art/cut.py, never served
const precache = files.filter((f) =>
  f !== 'icons/icon-1024.png' &&
  !f.startsWith('seed/') &&
  !DEAD.some((d) => f.startsWith(d)));

const hash = createHash('sha256');
for (const f of files) hash.update(f).update(readFileSync(join(ROOT, f)));
const VERSION = hash.digest('hex').slice(0, 12);

const sw = `/*
 * sw.js  ·  generated by build.mjs, do not edit by hand
 *
 * Cache first, always. Once installed, Triptych opens with no network at all
 * and never has to be refreshed. A new version only lands when this file's
 * VERSION changes, and it takes over the next time the app is launched.
 */

const VERSION = '${VERSION}';
const CACHE = 'triptych-' + VERSION;

const PRECACHE = [
  './',
${precache.map((f) => `  '${f}',`).join('\n')}
];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Fetch each one on its own so a single miss cannot fail the whole install.
    await Promise.all(PRECACHE.map(async (url) => {
      try {
        const res = await fetch(new Request(url, { cache: 'reload' }));
        if (res.ok) await cache.put(url, res);
      } catch { /* it will be picked up at runtime */ }
    }));
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith((async () => {
    const cached = await caches.match(req, { ignoreSearch: true });
    if (cached) return cached;

    try {
      const res = await fetch(req);
      if (res.ok && res.type === 'basic') {
        const cache = await caches.open(CACHE);
        cache.put(req, res.clone());
      }
      return res;
    } catch {
      if (req.mode === 'navigate') {
        const shell = await caches.match('./index.html', { ignoreSearch: true })
          || await caches.match('./', { ignoreSearch: true });
        if (shell) return shell;
      }
      return new Response('Offline and not cached.', { status: 504, statusText: 'Offline' });
    }
  })());
});

self.addEventListener('message', (event) => {
  if (event.data === 'skipWaiting') self.skipWaiting();
});
`;

writeFileSync(join(ROOT, 'sw.js'), sw);

const bytes = files.reduce((n, f) => n + statSync(join(ROOT, f)).size, 0);
console.log(`sw.js written · version ${VERSION} · ${precache.length} files · ${(bytes / 1024 / 1024).toFixed(2)} MB`);
