/*
 * sw.js  ·  generated by build.mjs, do not edit by hand
 *
 * Cache first, always. Once installed, Triptych opens with no network at all
 * and never has to be refreshed. A new version only lands when this file's
 * VERSION changes, and it takes over the next time the app is launched.
 */

const VERSION = 'b30df004eeb9';
const CACHE = 'triptych-' + VERSION;

const PRECACHE = [
  './',
  'CLAUDE.md',
  'assets/demons/camel.webp',
  'assets/demons/drummer.webp',
  'assets/demons/flower.webp',
  'assets/demons/goldfinch.webp',
  'assets/demons/iceSkater.webp',
  'assets/demons/index.json',
  'assets/demons/lobster.webp',
  'assets/demons/messenger.webp',
  'assets/demons/porcupine.webp',
  'assets/demons/prince.webp',
  'assets/demons/rabbit.webp',
  'assets/demons/skater.webp',
  'assets/demons/strawberry.webp',
  'assets/demons/wheelman.webp',
  'assets/demons/winged.webp',
  'assets/edge/bottom.webp',
  'assets/edge/left.webp',
  'assets/edge/rail.webp',
  'assets/edge/right.webp',
  'assets/edge/top.webp',
  'assets/frames/index.json',
  'assets/frames/landscape-1-page.webp',
  'assets/frames/landscape-1.webp',
  'assets/frames/landscape-2-page.webp',
  'assets/frames/landscape-2.webp',
  'assets/frames/landscape-3-page.webp',
  'assets/frames/landscape-3.webp',
  'assets/frames/landscape-4-page.webp',
  'assets/frames/landscape-4.webp',
  'assets/frames/portrait-1-page.webp',
  'assets/frames/portrait-1.webp',
  'assets/frames/portrait-2-page.webp',
  'assets/frames/portrait-2.webp',
  'assets/frames/portrait-3-page.webp',
  'assets/frames/portrait-3.webp',
  'assets/frames/portrait-4-page.webp',
  'assets/frames/portrait-4.webp',
  'assets/ground/page-dark.webp',
  'assets/ground/page-hell.webp',
  'assets/ground/page-light.webp',
  'assets/ground/page-mid.webp',
  'assets/ground/vellum-dark.webp',
  'assets/ground/vellum-hell.webp',
  'assets/ground/vellum-light.webp',
  'assets/ground/vellum-mid.webp',
  'css/bosch.css',
  'css/fonts.css',
  'fonts/v15-rnCr-xNNww_2s0amA9M3knjsS_ulYHs.woff2',
  'fonts/v15-rnCr-xNNww_2s0amA9M5knjsS_ul.woff2',
  'fonts/v15-rnCs-xNNww_2s0amA9uCt23BafaPWnII.woff2',
  'fonts/v15-rnCs-xNNww_2s0amA9uCt23PafaPWnIIMrY.woff2',
  'fonts/v15-rnCs-xNNww_2s0amA9vKsW3BafaPWnII.woff2',
  'fonts/v15-rnCs-xNNww_2s0amA9vKsW3PafaPWnIIMrY.woff2',
  'fonts/v15-rnCs-xNNww_2s0amA9vmtm3BafaPWnII.woff2',
  'fonts/v15-rnCs-xNNww_2s0amA9vmtm3PafaPWnIIMrY.woff2',
  'fonts/v15-rnCt-xNNww_2s0amA9M8onTmTNmnUHowCw.woff2',
  'fonts/v15-rnCt-xNNww_2s0amA9M8onrmTNmnUHo.woff2',
  'fonts/v21-co3bmX5slCNuHLi8bLeY9MK7whWMhyjYp3tKky2F7i6C.woff2',
  'fonts/v21-co3bmX5slCNuHLi8bLeY9MK7whWMhyjYqXtKky2F7g.woff2',
  'fonts/v21-co3smX5slCNuHLi8bLeY9MK7whWMhyjYrGFEsdtdc62E6zd58jD-htM8A_6pUKz9ugk.woff2',
  'fonts/v21-co3smX5slCNuHLi8bLeY9MK7whWMhyjYrGFEsdtdc62E6zd58jD-iNM8A_6pUKz9.woff2',
  'fonts/v22-WWXPlieVYwiGNomYU-ciRLRvEmK7oaVemGZMFABK1Q.woff2',
  'fonts/v33-SlGFmQSNjdsmc35JDF1K5GRwUjcdlttVFm-rI7e8QL99U6i1hGFJRvw.woff2',
  'fonts/v33-SlGFmQSNjdsmc35JDF1K5GRwUjcdlttVFm-rI7e8QL9zU6i1hGFJRvzr2Q.woff2',
  'fonts/v33-SlGUmQSNjdsmc35JDF1K5GR1SDk_YAPI.woff2',
  'fonts/v33-SlGUmQSNjdsmc35JDF1K5GR7SDk_YAPIlWk.woff2',
  'icons/apple-touch-icon.png',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'index.html',
  'js/app.js',
  'js/bestiary.js',
  'js/catalogue.js',
  'js/coach.js',
  'js/db.js',
  'js/dedication.js',
  'js/frames.js',
  'js/prefs.js',
  'js/reader.js',
  'js/summon.js',
  'manifest.webmanifest',
  'vendor/epub.min.js',
  'vendor/jszip.min.js',
];

self.addEventListener('install', (event) => {
  // Take over as soon as the new build is cached. Waiting for every tab to
  // close means a stale build can serve itself for days, and the code that
  // would have asked politely lives in the build the browser does not have.
  self.skipWaiting();
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Fetch each one on its own so a single miss cannot fail the whole install.
    await Promise.all(PRECACHE.map(async (url) => {
      try {
        const res = await fetch(new Request(url, { cache: 'reload' }));
        if (res.ok) await cache.put(url, res);
      } catch { /* it will be picked up at runtime */ }
    }));
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    let replaced = false;
    for (const key of await caches.keys()) {
      if (key !== CACHE) { await caches.delete(key); replaced = true; }
    }
    await self.clients.claim();

    // An old cache existed, so a page is running the previous build's scripts
    // against this one's files. Reload it rather than leave it half and half.
    // On a first install there is nothing to replace and nothing to reload.
    if (!replaced) return;
    for (const client of await self.clients.matchAll({ type: 'window' })) {
      try { await client.navigate(client.url); } catch { /* it will catch up */ }
    }
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith((async () => {
    // The document itself goes to the network first, with the cache as the
    // fallback. Answering navigations from the cache is what let a stale build
    // serve itself indefinitely, and ignoreSearch meant even a cache-busting
    // query came back stale.
    if (req.mode === 'navigate') {
      try {
        const fresh = await fetch(req);
        if (fresh && fresh.ok) {
          const cache = await caches.open(CACHE);
          cache.put('./index.html', fresh.clone());
          return fresh;
        }
      } catch { /* offline: fall through to what is stored */ }
      const shell = await caches.match('./index.html', { ignoreSearch: true })
        || await caches.match('./', { ignoreSearch: true });
      if (shell) return shell;
    }

    const cached = await caches.match(req, { ignoreSearch: true });
    if (cached) return cached;

    try {
      const res = await fetch(req);
      if (res.ok && res.type === 'basic') {
        const cache = await caches.open(CACHE);
        cache.put(req, res.clone());
      }
      return res;
    } catch {
      if (req.mode === 'navigate') {
        const shell = await caches.match('./index.html', { ignoreSearch: true })
          || await caches.match('./', { ignoreSearch: true });
        if (shell) return shell;
      }
      return new Response('Offline and not cached.', { status: 504, statusText: 'Offline' });
    }
  })());
});

self.addEventListener('message', (event) => {
  if (event.data === 'skipWaiting') self.skipWaiting();
});
