/*
 * sw.js  ·  generated by build.mjs, do not edit by hand
 *
 * Cache first, always. Once installed, Triptych opens with no network at all
 * and never has to be refreshed. A new version only lands when this file's
 * VERSION changes, and it takes over the next time the app is launched.
 */

const VERSION = '54bad02e2cb2';
const CACHE = 'triptych-' + VERSION;

const PRECACHE = [
  './',
  'CLAUDE.md',
  'assets/bands/amphibia.webp',
  'assets/bands/crowd.webp',
  'assets/bands/egg.webp',
  'assets/bands/fruit.webp',
  'assets/bands/instruments.webp',
  'assets/bands/pond.webp',
  'assets/bands/strawberryMan.webp',
  'assets/bands/treeFeet.webp',
  'assets/beasts/bagpipe.webp',
  'assets/beasts/beetle.webp',
  'assets/beasts/butterfly.webp',
  'assets/beasts/camel.webp',
  'assets/beasts/cerberus.webp',
  'assets/beasts/drum.webp',
  'assets/beasts/duckRider.webp',
  'assets/beasts/egg.webp',
  'assets/beasts/flower.webp',
  'assets/beasts/flutist.webp',
  'assets/beasts/goldfinch.webp',
  'assets/beasts/greenPerson.webp',
  'assets/beasts/iceSkater.webp',
  'assets/beasts/key.webp',
  'assets/beasts/lobster.webp',
  'assets/beasts/owl.webp',
  'assets/beasts/porcupine.webp',
  'assets/beasts/prince.webp',
  'assets/beasts/rabbit.webp',
  'assets/beasts/raven.webp',
  'assets/beasts/salamander.webp',
  'assets/beasts/skater.webp',
  'assets/beasts/strawberry.webp',
  'assets/beasts/treeDisk.webp',
  'assets/beasts/treeInside.webp',
  'assets/beasts/winged.webp',
  'assets/demons/camel.webp',
  'assets/demons/drummer.webp',
  'assets/demons/index.json',
  'assets/demons/messenger.webp',
  'assets/demons/porcupine.webp',
  'assets/demons/prince.webp',
  'assets/demons/rabbit.webp',
  'assets/demons/reader.webp',
  'assets/demons/skater.webp',
  'assets/demons/strawberry.webp',
  'assets/demons/wheelman.webp',
  'assets/edge/bottom.webp',
  'assets/edge/left.webp',
  'assets/edge/rail.webp',
  'assets/edge/right.webp',
  'assets/edge/top.webp',
  'assets/ground/page-dark.webp',
  'assets/ground/page-hell.webp',
  'assets/ground/page-light.webp',
  'assets/ground/page-mid.webp',
  'assets/ground/vellum-dark.webp',
  'assets/ground/vellum-hell.webp',
  'assets/ground/vellum-light.webp',
  'assets/ground/vellum-mid.webp',
  'assets/ink/butterfly.webp',
  'assets/ink/flower.webp',
  'assets/ink/goldfinch.webp',
  'assets/ink/iceSkater.webp',
  'assets/ink/index.json',
  'assets/ink/key.webp',
  'assets/ink/owl.webp',
  'assets/ink/porcupine.webp',
  'assets/ink/rabbit.webp',
  'assets/ink/skater.webp',
  'assets/ink/winged.webp',
  'css/bosch.css',
  'css/fonts.css',
  'fonts/v15-rnCr-xNNww_2s0amA9M3knjsS_ulYHs.woff2',
  'fonts/v15-rnCr-xNNww_2s0amA9M5knjsS_ul.woff2',
  'fonts/v15-rnCs-xNNww_2s0amA9uCt23BafaPWnII.woff2',
  'fonts/v15-rnCs-xNNww_2s0amA9uCt23PafaPWnIIMrY.woff2',
  'fonts/v15-rnCs-xNNww_2s0amA9vKsW3BafaPWnII.woff2',
  'fonts/v15-rnCs-xNNww_2s0amA9vKsW3PafaPWnIIMrY.woff2',
  'fonts/v15-rnCs-xNNww_2s0amA9vmtm3BafaPWnII.woff2',
  'fonts/v15-rnCs-xNNww_2s0amA9vmtm3PafaPWnIIMrY.woff2',
  'fonts/v15-rnCt-xNNww_2s0amA9M8onTmTNmnUHowCw.woff2',
  'fonts/v15-rnCt-xNNww_2s0amA9M8onrmTNmnUHo.woff2',
  'fonts/v21-co3bmX5slCNuHLi8bLeY9MK7whWMhyjYp3tKky2F7i6C.woff2',
  'fonts/v21-co3bmX5slCNuHLi8bLeY9MK7whWMhyjYqXtKky2F7g.woff2',
  'fonts/v21-co3smX5slCNuHLi8bLeY9MK7whWMhyjYrGFEsdtdc62E6zd58jD-htM8A_6pUKz9ugk.woff2',
  'fonts/v21-co3smX5slCNuHLi8bLeY9MK7whWMhyjYrGFEsdtdc62E6zd58jD-iNM8A_6pUKz9.woff2',
  'fonts/v22-WWXPlieVYwiGNomYU-ciRLRvEmK7oaVemGZMFABK1Q.woff2',
  'fonts/v33-SlGFmQSNjdsmc35JDF1K5GRwUjcdlttVFm-rI7e8QL99U6i1hGFJRvw.woff2',
  'fonts/v33-SlGFmQSNjdsmc35JDF1K5GRwUjcdlttVFm-rI7e8QL9zU6i1hGFJRvzr2Q.woff2',
  'fonts/v33-SlGUmQSNjdsmc35JDF1K5GR1SDk_YAPI.woff2',
  'fonts/v33-SlGUmQSNjdsmc35JDF1K5GR7SDk_YAPIlWk.woff2',
  'icons/apple-touch-icon.png',
  'icons/icon-120.png',
  'icons/icon-152.png',
  'icons/icon-167.png',
  'icons/icon-180.png',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'index.html',
  'js/app.js',
  'js/bestiary.js',
  'js/db.js',
  'js/dedication.js',
  'js/prefs.js',
  'js/reader.js',
  'js/summon.js',
  'manifest.webmanifest',
  'vendor/epub.min.js',
  'vendor/jszip.min.js',
];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Fetch each one on its own so a single miss cannot fail the whole install.
    await Promise.all(PRECACHE.map(async (url) => {
      try {
        const res = await fetch(new Request(url, { cache: 'reload' }));
        if (res.ok) await cache.put(url, res);
      } catch { /* it will be picked up at runtime */ }
    }));
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith((async () => {
    const cached = await caches.match(req, { ignoreSearch: true });
    if (cached) return cached;

    try {
      const res = await fetch(req);
      if (res.ok && res.type === 'basic') {
        const cache = await caches.open(CACHE);
        cache.put(req, res.clone());
      }
      return res;
    } catch {
      if (req.mode === 'navigate') {
        const shell = await caches.match('./index.html', { ignoreSearch: true })
          || await caches.match('./', { ignoreSearch: true });
        if (shell) return shell;
      }
      return new Response('Offline and not cached.', { status: 504, statusText: 'Offline' });
    }
  })());
});

self.addEventListener('message', (event) => {
  if (event.data === 'skipWaiting') self.skipWaiting();
});
